spring.application.name=lets-play
spring.config.import=optional:file:.env[.properties]
spring.mongodb.uri=mongodb+srv://${MONGO_USERNAME}:${MONGO_PASSWORD}@lets-play.iw9bben.mongodb.net/abu?appName=Lets-Play
# spring.mongodb.database=abu
spring.data.mongodb.auto-index-creation=true
